# Generated by Django 3.2.7 on 2023-03-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=150)),
                ('file', models.FileField(max_length=200, upload_to='')),
                ('result', models.CharField(max_length=150)),
            ],
        ),
    ]
